
curl 'https://kugfuumoqyxqowtnrujk.supabase.co/rest/v1/facts' 
-H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z2Z1dW1vcXl4cW93dG5ydWprIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3MTE2MjA4OSwiZXhwIjoxOTg2NzM4MDg5fQ.n6shKyD0s0DlhLHLc-Wy7Wk9VwR0E4aOC7anDnmxeQQ" 
-H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt1Z2Z1dW1vcXl4cW93dG5ydWprIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTY3MTE2MjA4OSwiZXhwIjoxOTg2NzM4MDg5fQ.n6shKyD0s0DlhLHLc-Wy7Wk9VwR0E4aOC7anDnmxeQQ"
